# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63994cf7f80ea1e76dd11738888afc34bac5647415c4977c445e02cbade75d4fb37ccf0a9f053ba277be89ad4e8a88db99fb1724e4e58213684fe393fb730d18
  google_map: <%= ENV["GOOGLEMAP"] %>

test:
  secret_key_base: b959b384b5e22fb1bbd6810002227929c8c734e650e122123254640c1012ca7754b67589b5c9807e773e8ce37af74c2078fdf087b0333ecfbda6dba66c72364a
  google_map: <%= ENV["GOOGLEMAP"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_map: <%= ENV["GOOGLEMAP"] %>